### PR TITLE
Introduce source file output feature

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by FroMage** [comment]
This looks great. How do I get the same with files generated with ASM? :)

**Comment by dmlloyd** [comment]
That'd be a little bit more of a challenge. :)  Possible though!

**Comment by dmlloyd** [comment]
Any further thoughts?  Shall I merge?

**Comment by FroMage** [comment]
I would use that, and my IDE does not have a disassembler by default.

**Pull request merged**
