### PR TITLE
Add nested AnnotationCreator alternative; add Javadoc for AnnotationCreator

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
Add a new method to support creating nested annotations using
AnnotationCreators. It works by creating a new AnnotationCreator
and adding its value map as a value to the parent AnnotationCreator
(thus any changes made to the nested AnnotationCreator update the
map in the parent's values). Also added Javadoc so these features
are discoverable.

### CODE REVIEW

**Comment by Ladicek** [comment]
Hi @Christopher-Chianelli, I looked into this too, because I figured my suggestion to add `AnnotationCreator addNested` was not very well thought through. Instead, I came up with this: https://github.com/quarkusio/gizmo/compare/main...Ladicek:nested-annotation-creator?expand=1 I believe it nicely replaces the `Map` usage as well as the various `addNested` methods. WDYT?

**Comment by Christopher-Chianelli** [comment]
Greetings @Ladicek ; Looking at https://github.com/quarkusio/gizmo/compare/main...Ladicek:nested-annotation-creator?expand=1 , I agree it nicely replaces the Map usage and offer a better API than this PR. `Map` was used since I needed a type that:

- Users are already familiar with
- Supports keys and values
- Is easy to create (Jandex `AnnotationInstance` is not easy to create)

`AnnotationCreator` also support each of the above, while also naturally representing annotations. The code in the branch LGTM.

**Comment by Ladicek** [comment]
I'll submit a PR then, thank you!

**Comment by mkouba** [comment]
I'm going to close this PR in favor of https://github.com/quarkusio/gizmo/pull/111.

**Pull request closed without merging**
