### PR TITLE
Revert "Do not attempt to load JDK classes from the TCCL"

### PR DESCRIPTION
**Pull request by zakkak**
@geoand unfortunately #126 results in https://github.com/quarkusio/quarkus/issues/28431

I have added a new test to for `java.lang` that demonstrates this.

### CODE REVIEW

**Review by geoand — APPROVED** [review]
Thanks for the test

**Comment by gsmet** [comment]
Wouldn't it be possible to not use the TCCL but keep the `Class.forName` approach?

Not sure if it would buy us anything though.

**Comment by geoand** [comment]
What I'll probably end up doing is just keeping a list of classes were we can safely do what I did in the previous PR

**Comment by geoand** [comment]
https://github.com/quarkusio/gizmo/pull/138 is what I have in mind. Not pretty, but should cover most of the usages we have in Quarkus

**Pull request merged**
