### PR TITLE
add signature generation in classCreator

### LINKED ISSUE #66: Simplify the handling of parameterized types
Right now, you need to use `signature` passing it a complex string describing how your type is parameterized. It would be nice if that complexity could be hidden away.

### PR DESCRIPTION
**Pull request by dufoli**
fix #66

### CODE REVIEW

**Comment by dufoli** [comment]
OK, So I have now a code to handle generics. Need to check with a lot of unit test that all work together. between jandex ParameterizedType,  Field, FieldInfo, MethodInfo, Method, ....

**Comment by dufoli** [comment]
I have removed the deep integration with just an util helper class to generate signature. I have still some code remaining (formalType and few other for futur use) anyway I let you review and I will cleanup it if not need/usefull for futur used...

**Comment by dufoli** [comment]
@gsmet @stuartwdouglas @Sanne  can you review it ?

**Comment by mkouba** [comment]
This pull request was superseded by https://github.com/quarkusio/gizmo/pull/147.

**Pull request closed without merging**
