### PR TITLE
Use ASM7 api code instead of ASM6 when instantiating GizmoClassVisitor

### PR DESCRIPTION
**Pull request by gwenneg**
Resolves https://github.com/quarkusio/quarkus/issues/2894

### CODE REVIEW

**Comment by gsmet** [comment]
@stuartwdouglas or @cescoffier we would need a Gizmo release with this fix in.

Preferably for the next Quarkus release (there's a chance I'll push a new one on Wednesday with the GraalVM 19 support).

**Comment by cescoffier** [comment]
Ok, I will cut a release of gizmo today.

**Comment by gsmet** [comment]
@cescoffier thanks!

**Comment by cescoffier** [comment]
@gsmet Release done. It's on central (http://repo1.maven.org/maven2/io/quarkus/gizmo/gizmo/1.0.0.Alpha5/)

**Comment by gsmet** [comment]
@cescoffier cool thanks, I'll push an upgrade PR soon.

**Pull request merged**
